### ISSUE TITLE
Course audit - April 2019

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/intro-to-html#17]
Course audit, April 2019

**Comment by beardofedu** [comment]
@hectorsector when the course audit is completed, can we `filter-branch` the commits so you or I are no longer the commit author so we stop getting pings when people work on the course?

**Comment by brianamarie** [comment]
I am happy to do this - @hectorsector is it OK if I change history so @beardofedu is no longer the author of the initial commit on all branches, then force push up to the template repo and re-sync it?

**Comment by brianamarie** [comment]
Great! I've gone through and filter-branched on all of the branches, force pushed 'em up, and resynced the course. I tested it to make sure it would still work, and all is good. @beardofedu you should be off the hook!

**Comment by brianamarie** [comment]
Closing since this is long past!
